spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/nexxus}
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    username: ${DATABASE_USERNAME:admin}
    password: ${DATABASE_PASSWORD:admin}
    hikari:
      maximum-pool-size: ${DATABASE_MAX_POOL_SIZE:10}
      minimum-idle: ${DATABASE_MIN_IDLE:5}
      connection-timeout: ${DATABASE_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DATABASE_IDLE_TIMEOUT:600000}
      max-lifetime: ${DATABASE_MAX_LIFETIME:1800000}

server:
  port: ${SERVER_PORT:8000}

logging:
  level:
    com.nexxus: ${LOG_LEVEL:DEBUG}
    org.springframework.jdbc: ${JDBC_LOG_LEVEL:INFO}
