# Nexxus Backend Application Configuration
# This file imports shared configuration from libs/shared
# All configuration values are now managed via environment variables in .env file

spring:
  application:
    name: ${SPRING_APPLICATION_NAME:nexxus-core}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import:
      - optional:classpath:/application-common.yml

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:ALWAYS}
