/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.7/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
	alias(libs.plugins.spring.boot)
	alias(libs.plugins.spring.dependency.management)
	java
}

repositories {
	mavenCentral()
}

dependencies {
	implementation(libs.spring.boot.starter.web)
	implementation(libs.spring.boot.starter.jdbc)
	runtimeOnly(libs.postgresql)
	runtimeOnly(libs.h2)

	testImplementation(libs.spring.boot.starter.test)
}

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(21)
	}
}

// Set the main class explicitly for clarity
springBoot {
	mainClass.set("com.nexxus.NexxusBackendApplication")
}

tasks.named<Test>("test") {
	useJUnitPlatform()
}
