server:
  port: ${ORDER_SERVICE_PORT}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      probes:
        enabled: true

spring:
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    show-sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${ORDER_DB_URL}
    username: ${ORDER_DB_USERNAME}
    password: ${ORDER_DB_PASSWORD}

