server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/exxus_jobs
    username: exxus
    password: secret

org:
  jobrunr:
    background-job-server:
      enabled: true
    dashboard:
      enabled: true
      port: 8000

