/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    // Apply the common convention plugin for shared build configuration between library and application projects.
    id("build.common")

    // Apply the Java plugin for basic Java project configuration
    id("java")

    // Apply the application plugin to add support for building a CLI application in Java.
    id("application")
}
