/*
 * This file was generated by the Gradle 'init' task.
 */

import org.gradle.api.tasks.compile.JavaCompile

plugins {
    // Spotless for code formatting
    id("com.diffplug.spotless")
}

repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

// Java compilation options to preserve parameter names for reflection
tasks.withType<JavaCompile> {
    options.compilerArgs.add("-parameters")
}

// Spotless configuration for code formatting
spotless {
    java {
        // Use Google Java Format
        googleJavaFormat("1.19.2")
        
        // Import organization
        importOrder(
            "java",
            "javax",
            "org",
            "com",
            "nexxus"
        )
        
        // Remove unused imports
        removeUnusedImports()
    }
}